### ISSUE TITLE
syntax error running `bts`

### ISSUE THREAD

**Issue by nmushegian** [wackou/bts_tools#18]
```
Traceback (most recent call last):
  File "/usr/local/bin/bts", line 9, in <module>
    load_entry_point('bts-tools==0.1-dev', 'console_scripts', 'bts')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/bts_tools-0.1_dev-py2.7.egg/bts_tools/__init__.py", line 29, in <module>
    from .rpcutils import main_node as rpc
  File "/usr/local/lib/python2.7/dist-packages/bts_tools-0.1_dev-py2.7.egg/bts_tools/rpcutils.py", line 183
    def call(*args, cached=True):
```

**Comment by wackou** [comment]
yeah, the doc is not completely clear about this (yet, will update this weekend), but you need python3 to run it, python2 doesn't cut it anymore...

**Comment by wackou** [comment]
Note: you can ensure you use python3 by installing the tools with ``pip3 install bts_tools`` instead of ``pip install bts_tools``
